# Generated by Django 5.1.1 on 2024-10-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=150, unique=True)),
                ('lastName', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
        ),
    ]
